version: '3'
services:
  master1:
    image: hadoop
    stdin_open: true
    tty: true
    command: bash
    hostname: hadoop330
    ports:
      - "9000:9000"
      - "9870:9870"
      - "8088:8088"
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    networks:
      mynetwork:
        ipv4_address: 192.168.1.4 

  master2:
    image: hadoop
    stdin_open: true
    tty: true
    command: bash
    networks:
      mynetwork:
        ipv4_address: 192.168.1.5 
  
  worker1:
    image: hadoop
    stdin_open: true
    tty: true
    command: bash
    environment:
      - START_ZOOKEEPER=true 
    networks:
      mynetwork:
        ipv4_address: 192.168.1.1     

  worker2:
    image: hadoop
    stdin_open: true
    tty: true
    command: bash
    environment:
      - START_ZOOKEEPER=true 
    networks:
      mynetwork:
        ipv4_address: 192.168.1.2 

  worker3:
    image: hadoop
    stdin_open: true
    tty: true
    command: bash
    environment:
      - START_ZOOKEEPER=true
    networks:
      mynetwork:
        ipv4_address: 192.168.1.3  


networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/16"